version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: 'develop-stage'
    image: javi98/vue-test-client:1.0.0
    container_name: vue-test-client-app
    command: /bin/sh -c "yarn && quasar dev"
    ports:
      - '9000:9000'
    volumes:
      - '.:/src'
      - /src/node_modules
  json-server:
    image: clue/json-server
    container_name: vue-test-client-json-server
    ports:
      - "3000:80"
    volumes:
      - ./docker-config/json-server:/data
    restart: always